[package]
name = "mo-build"
description = "MoInstaller builder CLI（命令名 mo）：读 TOML 清单，产出单文件 setup.exe"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[lib]
name = "mo_build"
path = "src/lib.rs"

[[bin]]
name = "mo"
path = "src/main.rs"

[dependencies]
mo-core = { workspace = true }
mo-script = { path = "../mo-script" }
anyhow = { workspace = true }
clap = { workspace = true }
glob = { workspace = true }
